CREATE TABLE test_interview_template(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    UNIQUE(title)
)

CREATE TABLE test_interview_template_questions(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    tag_id INT NOT NULL,
    questions_count INT NOT NULL,
    template_id INT NOT NULL,
    
    CONSTRAINT unique_tag_info
        UNIQUE(tag_id, template_id),
    
    CONSTRAINT fk_test_interview_template
        FOREIGN KEY(template_id)
        REFERENCES test_interview_template(id)
        ON DELETE CASCADE
)